apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-to-number-api-deployment
  labels:
    app: image-to-number-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-to-number-api
  template:
    metadata:
      labels:
        app: image-to-number-api
    spec:
      containers:
      - name: image-to-number-api
        image: image-to-number-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
