apiVersion: v1
kind: Service
metadata:
  name: image-to-number-api-service
  labels:
    app: image-to-number-api
spec:
  selector:
    app: image-to-number-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
