apiVersion: v1
kind: Service
metadata:
  name: text-to-speech-service
  labels:
    app: text-to-speech
spec:
  selector:
    app: text-to-speech
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
