apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-to-speech-api-deployment
  labels:
    app: word-to-speech-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-to-speech-api
  template:
    metadata:
      labels:
        app: word-to-speech-api
    spec:
      containers:
      - name: word-to-speech-api
        image: word-to-speech-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
