apiVersion: v1
kind: Service
metadata:
  name: word-to-speech-api-service
  labels:
    app: word-to-speech-api
spec:
  selector:
    app: word-to-speech-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
